<a href="https://colab.research.google.com/github/gurjotsingh1404/Fast.ai/blob/main/Torch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('hello')

hello


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as  np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [ ]:
##Introduction to tensors
#creating tensors

#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# pytorch tensors are created using Torch.tensor https://pytorch.org/docs/stable/tensors.html

In [ ]:
scalar.ndim # no of dimension = 0 as its a regualr number

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
print("How many dimensions does the matrix have?")
MATRIX.ndim


How many dimensions does the matrix have?


2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape
#Basically pehli dimension me(0th dimension) 3 array hain ,
#har array me 3 items hain. -> 1,3,3

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
 TENSOR[1]

IndexError: ignored

In [ ]:
kencer = torch.tensor([[[1,2],[3,4]]])
kencer.ndim

In [ ]:
tensor = torch.Tensor([[[1,2,3],[1,2,3],[1,2,3]],
                      [[4,5,6],[4,5,6],[4,5,6]],
                      [[7,8,9],[7,8,9],[7,8,9]]])
tensor.shape

In [ ]:
tensor.ndim

In [ ]:
print(Tensor)

### `RANDOM TENSORS`

*Why* random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and adjust those random numbers to better represent the data.

DOC : https://pytorch.org/docs/stable/generated/torch.rand.html



`Start with random numbers -> look at data -> update random numbers -> look at data ->update the random numbers`


In [ ]:
# creating a random tensors of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

In [ ]:
random_tensor.ndim

In [ ]:
lamba_tensor = torch.rand(4,4,5)
lamba_tensor

In [ ]:
lamba_tensor.ndim

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3,224,224))#height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim


### Zeroes and ones

In [ ]:
#Create a tensor of all zeroes( used in masking)
zeros = torch.zeros(size=(4,4,5))
zeros


In [ ]:
zeros*lamba_tensor

In [ ]:
#MASKING OUT FIRST COLUMN, etc


In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

In [ ]:
ones.dtype # data type = torch.float 32

### Creating a range of tensor and tensor- like

In [ ]:
zero_to_ten = torch.arange(0,9)
zero_to_ten

In [ ]:
naya = torch.arange(start = 1, end = 23, step = 2)
naya

In [ ]:
# create tensors like
tees_zeroes = torch.zeros_like(input = naya)
tees_zeroes

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big erros that we will run into with in
PyTorch and Deep Learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, #what datatype is the tensor(eg. float32 or float 16)
                               device = None,#what device is your data on
                               requires_grad = False) #whether or not to track gradients with this tensors operations
float_32_tensor

In [ ]:
float_32_tensor.dtype

In [ ]:
#changing the tensor datatype

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

In [ ]:
float_16_tensor*float_32_tensor

In [ ]:
float_16_tensor.dtype

###  Multipyling tensors

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

In [ ]:
mera_answer = int_32_tensor*float_32_tensor
mera_answer.dtype

In [ ]:
# How to change the data type of a tensor
mera_answer = mera_answer.to(dtype = torch.int32)
mera_answer.dtype

### Getting information from tensors(tensor attributes)


1. Tensors in not right datatype - to  get datatype from a tensor, use `tensor.dtype`
2. Tensors in not right shape - to get shape from a tensor, use `tensor.dtype`
3. Tensors on  right device - to get the device from a tensor, use `tensor,device`


.shape - attribute without the curly braces


.size{} - function- with curly braces

both will return the same value


In [ ]:
#Create a tensor and try these
try_kro = torch.rand(3,4)
try_kro

In [ ]:
#Find out details about try karo
print(try_kro)
print(f"Datetype of tensor:{try_kro.dtype}")
print(f"Shape of tensor: {try_kro.shape}")
print(f"Device of tensor: {try_kro.device}")


### Manipulating Tensors(tensor operations)

Tensor operations include:




*Addition

*Subtraction

*Multiplication(element - wise)

*Division

*Matrix Multiplication



In [ ]:
#Creat a tensor and 10 added to it
tensor = torch.tensor([1,2,3])
tensor = tensor + 10
tensor

In [ ]:
# Multiplying by 10
tensor = tensor*10

In [ ]:
tensor = tensor - 10
tensor


In [ ]:
 #Pytorch inbuilt functions
 torch.mul(tensor, 10)

In [ ]:
torch.add(tensor, 1)

### MATRIX MULTIPLICATION

Two ways of multiplication in NN AND AL

1. Element wise multiplication
2. MATRIX Multiplication(DOT PRODUCT)


TWO MAIN rules for performing matrix multiplication:

1 **the innner dimensions** must much:
(3,2)*(3,2) wont work
(2,3)*(3,2) will work

simple matrix multiplication rules



2 The resulting matrix has the shape of the **outer dimensions**

(3,2)*(2,4) == (3,4)



In [ ]:
# Element wise
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

In [ ]:
#MATRIX MULTIPLICATION
torch.matmul(tensor, tensor) #always use the given method it is much fast than by self

In [ ]:
torch.matmul(torch.rand(3,6), torch.rand(6,7)).shape

### One of the most common errors in deep learning : shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A, tensor_B) # matmul -> mm

In [ ]:
tensor_A.shape, tensor_B.shape

To fix our tensor shape issues, we can manipulate the shape of one of our tensor  using transpose



In [ ]:
tensor_B, tensor_B.shape

In [ ]:
tensor_B.T, tensor_B.T. shape

In [ ]:
# The matrix multiplication is when tensor_B is transposed

print(f"The original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes:  tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f" Multipying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


### Tensor Aggregation

Finding Min, Max, Mean, Sum, etc

In [ ]:
x =torch.arange(0,100,10)
x.dtype

In [ ]:
#Find the min
torch.min(x), x.min()

In [ ]:
# Find the max
torch.max(x), x.max(x)

In [ ]:
#Find the mean (WRONG DATA TYPE ERROR !!!!!!!!!!!!!!!)
#Notw: The torch.mean requires a tensor of float 32 datatype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
#Find the sum
torch.sum(x), x.sum()

###Finding the positional min and max( Returns the index)

*   List item
*   List item



In [ ]:
x


In [ ]:
# Find the position in tensor which has the min value   -> returns its index
x.argmin()

In [ ]:
x[0]

In [ ]:
#Find the position in tensor with the max value
x.argmax()

## Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an inout tensor to a defined shape.

*View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.

*Stacking - Combine multiple tensors on top of each other (vstack) ir side by side stack(hstack)

*Squeeze - removes all `1` dimensions to a target tensor
*Unsqueeze - add a `1` dimenions to a target tensor

*Permute - Return a view of the input with dimensions permuted(swapped) in a certain way.


In [ ]:
#lets create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape


In [ ]:
#Add an extrea dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

In [ ]:
#Change the view
z = x.view(1,9)
x, x.shape

In [ ]:
# Changing z changes x(because a view of a tensor shares the same memory as the original input)

In [ ]:
z[:, 0] = 5 # we changed the first element of z and it also changed in x, as z is a view of x
z,x

In [ ]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

In [ ]:
#torch.squeeze() - removes all single dimensions from a target tensor

x = torch.zeros(2,1,2,1,2)


In [ ]:
y = torch.squeeze(x)
y.size()

In [ ]:
y = torch.squeeze(x,0)
y.size()

In [ ]:
x_reshaped

In [ ]:
x_reshaped.shape

In [ ]:
x_reshaped.squeeze()

In [ ]:
z = x_reshaped.squeeze().shape

In [ ]:
z.squeeze().shape

`Uper wale me se 1 dimension wale uda diye hain, elements remain in the tensor, just the way of representation changes

In [ ]:
# Make a habit of doing this visualization using printing and seeing how the tensor looks
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\n New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

In [ ]:
#torch.unsqueezed() - adds a single dimensions to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimension with squeeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0) # added a square bracket at the dimension 0
print(f"\n New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


In [ ]:
 x_squeezed.unsqueeze(dim = 1)

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

Every time there is a parameter in a pytorch function, try to change and play with to get an idea of the functionality

In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in  a specified order
# usually used in image data tensors

x_original = torch.rand(size =(224, 224, 3)) #[height, width, color_channels

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0 , 1) #shifts axis 0->1, 1->2, 2->1
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape} ") # Now this is [color_channels, height, width, shape badal gyi pr notice kre ki values same hi hain]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224]) 


In [ ]:
x_original[0, 0, 0] = 723489
print(f"Previous tensor: {x_original}")
print(f"Previous tensor shape: {x_original.shape}")
print(f"New shape: {x_original.permute(2, 0, 1).shape}")


Previous tensor: tensor([[[723489]]])
Previous tensor shape: torch.Size([1, 1, 1])
New shape: torch.Size([1, 1, 1])


In [ ]:

# Modify the element
x_original = torch.tensor([[[723489]]])

# Print the changed value
print(x_original)

tensor([[[723489]]])


## Indexing (Selecting data from tensors)

Index with Pytorch is similar to numPy

In [ ]:
#Create a tensor
import torch
x = torch.arange(1,10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Lets's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim =1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket( last dimension)
x[1][1][1]

IndexError: ignored

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
numer_9 = x[0][2][2]
numer_9

tensor(9)

In [ ]:
#You can also use ";" to select "all" of a target dimension
x[:,2]

tensor([[7, 8, 9]])

In [ ]:
#Get all values of all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, : ,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1] # got the same answer as x[0][1][1]

tensor([5])

Same answer but the output here has is in the sqaure brackets as it returns the `dimensions` and the earlier code onyl returned the `particular value`.

** To be kept in mind

In [ ]:
#Get index 0 of 0th dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [ ]:
#Index on x to return 9
x[:,2,2]


tensor([9])

In [ ]:
# Index on x to return 3 6 9
x[:, : ,2]

tensor([[3, 6, 9]])

In [ ]:
# OR

print(x[0][2][2])

print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library.

* Data in NumPy, want in PyTorch tensor-> `torch.from_numpy(ndarray)

* PyTorch tensor->NumPy-> `torch.Tensor.numpy()

In [ ]:
#NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype


torch.float64

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

## NOTE

* When you are going from numPY to PyTorch
NumPy dtype = float64 and after getting converted to a tensor it will still reflect float32.

* Whereas a tensor created by PyTorch is of dtype = float32

In [ ]:
# changing the dtype directly while making the conversion

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
tensor.dtype

torch.float32

** oh yeah

In [ ]:
#Change the value of array, what will this to `tensor`


In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

**Veridict : it changes the value of the original array and not the tensor it was converted into**



In [ ]:
# Tensor to NumPy -> is float32
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Change the tensor, what happems to `numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# numpy tensor rem,ained unchanged, means they dont share any memory

## Reproducibility(trying to take the random out of random)

In short how a neural network learns:

`start with random numbers-> tensor operations-> update random numbers to try and make them better represenations of the data-> again-> again-> again...`


To reduce the randomness in neural networks and pytorch comes the concept of a `random seed`

Essentially what the random seed does is "flavour" the randomness

In [ ]:
import torch


#Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1484, 0.5889, 0.8698, 0.0613],
        [0.2451, 0.8336, 0.8612, 0.6512],
        [0.8945, 0.0753, 0.4272, 0.6150]])
tensor([[0.3818, 0.1984, 0.7609, 0.2993],
        [0.4083, 0.3468, 0.8854, 0.4056],
        [0.3601, 0.9861, 0.7352, 0.4560]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
1 == 1

True

In [ ]:
#Lets make some random but reproducible tensors
import torch

#Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

#if u are creating random tensors one after the other u need to call torch.manual everytime
#Otherwise for other torch processes, just the random_seed needs to be assigned at the start of the code and it will do its job
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## RESOURCES FOR RANDOM SEED

* https://pytorch.org/docs/stable/notes/randomness.html

* https://en.wikipedia.org/wiki/Random_seed

## Runnning tensors and PyTorch objects on GPU

GPU = FASTER COMPUTATION

1> google collab
2> Own GPU
3> Use cloud computing - GCP, AWS, Azure.

For GPU Setup

In [ ]:
#CHECK FOR GPU ACCess with pytorch
import torch
torch.cuda.is_available()

False

In [ ]:
#Setup device agnostic code as tensors can run on GPU or CPU
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

SyntaxError: ignored

In [ ]:
torch.cuda.device_count()

0

https://pytorch.org/docs/stable/notes/cuda.html

## Putting tensors(and models) on the GPU


In [ ]:
# Create a tensor ( default on the CPU)
tensor = torch.tensor([1, 2, 3])

#Tensor not on CPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to gpu if avaialable
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cpu')

### moving tensors back to CPU

* Numpy works only on the cpu, hence have to be converted back

In [ ]:
# if tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [ ]:
# To fix the GPU tensor with numPy issue, we cam first set it to the CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

### EXERCISES

https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

